### ISSUE TITLE
Management commands needed to enable/disable switches

### ISSUE THREAD

**Issue by rassie** [django-waffle/django-waffle#10]
I've got an application which has a certain feature which is only useful when a big load of data is loaded into the database. I would like to do something like this:

```
$ ./manage.py switch_off my_feature
$ ./manage.py loaddata fixtures/my_big_pile_of_data.json
$ ./manage.py switch_on my_feature
```

This would obviously require the `switch_on` and `switch_off` commands to be implemented. Any chance this will appear soon?

**Comment by jsocol** [comment]
Interesting idea! It's easy to extend to Samples but difficult to extend to Flags.

**Comment by rassie** [comment]
I actually only thought about Switches. Flags would certainly be possible too with something like `./manage.py flag authenticated on`, but it's way more complicated than Switches and Samples.

**Comment by jsocol** [comment]
It's not the highest priority for me, honestly, but it doesn't seem like a patch would be terribly difficult, especially just for Switches. I'd use syntax like `./manage.py switch my_switch on/off`. Otherwise I might get to it in a 0.9?

**Comment by rassie** [comment]
No urge :-) The patch shouldn't be that difficult indeed, so if I happen to implement it before you do, you'll get a pull request.

**Comment by mwarkentin** [comment]
I've added to what @cyberdelia has done [here](https://github.com/cyberdelia/django-waffle/pull/1)

**Comment by mwarkentin** [comment]
Any thoughts on the pull request? I should have a bit of time to make any updates that you think are needed.

**Comment by jsocol** [comment]
Sorry, I've been swamped the past couple weeks. Let me dig into it today.

**Comment by mwarkentin** [comment]
No worries, whenever you have a chance.

Thanks for the great tool!

**Comment by jsocol** [comment]
Think this was all solved by https://github.com/jsocol/django-waffle/compare/9abbbebb%5E...9c9aa5c
