### ISSUE TITLE
ImportError: cannot import name Flag

### ISSUE THREAD

**Issue by dsimandl** [django-waffle/django-waffle#105]
> ImportError: cannot import name Flag 

I get this error when I also run syncdb or when I try to run a migration via South. This is on Django 1.5.4/Python 2.7.1.  I have django.core.context_processors.request in my TEMPLATE_CONTEXT_PROCESSORS and waffle.middleware.WaffleMiddleware in my MIDDLEWARE_CLASSES as per the django-waffle documentation.

Here is the Traceback when I tried to run a syncdb...

> Traceback (most recent call last): File "manage.py", line 10, in >execute_from_command_line(sys.argv)
> 
> File "/Users/Dropbox/virtualenviroments/lib/python2.7/site-packages/django>/core/management/init.py", line 453, in execute_from_command_line utility.execute()
> 
> File "/Users/Dropbox/virtualenviroments/lib/python2.7/site-packages/django/core/management/init.py", line 392, in execute self.fetch_command(subcommand).run_from_argv(self.argv)
> 
> File "/Users/Dropbox/virtualenviroments/lib/python2.7/site-packages/django/core/management/init.py", line 272, in fetch_command klass = load_command_class(app_name, subcommand)
> 
> File "/Users/Dropbox/virtualenviroments/lib/python2.7/site-packages/django/core/management/init.py", line 77, in load_command_class module = import_module('%s.management.commands.%s' % (app_name, name))
> 
> File "/Users/Dropbox/virtualenviroments/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module import(name)
> 
> File "/Users/Dropbox/virtualenviroments/lib/python2.7/site-packages/south/management/commands/init.py", line 10, in import django.template.loaders.app_directories
> 
> File "/Users/Dropbox/virtualenviroments/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 25, in raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
> 
> django.core.exceptions.ImproperlyConfigured: ImportError waffle: cannot import name Flag

**Comment by kitsunde** [comment]
I'm seeing the same issue in Django 1.6 on runserver and syncdb.

**Comment by kpachnis** [comment]
I had similar issues in both Django 1.5 and 1.6 after upgrading to the latest version of django-debug-toolbar. I have used the [explicit setup instructions](http://django-debug-toolbar.readthedocs.org/en/1.0/installation.html#explicit-setup) and everything works fine.

**Comment by jsocol** [comment]
Did anyone test @kpachnis's fix? I've never run into this but I don't often turn on debug toolbar these days.

**Comment by kpachnis** [comment]
There is not actually a fix, just the instructions from the debug-toolbar documentation.

**Comment by jsocol** [comment]
@kpachnis Your last comment made it sound like the issue was fixed by those instructions. [This commit](https://github.com/ccnmtl/ccnmtldjango/commit/4fe16810bf8fb3290ade979206926a28e73b7f9f) and the linked issue at ccnmtl also seem to make it sound fixed.

**Comment by kpachnis** [comment]
@jsocol Yes, it did. 
I think it would be better to say: Following the [explicit setup](http://django-debug-toolbar.readthedocs.org/en/1.0/installation.html#explicit-setup) instructions from the django-debug-toolbar documentation will fix this issue.
