### ISSUE TITLE
New pypi release?

### ISSUE THREAD

**Issue by MatMoore** [django-waffle/django-waffle#110]
Hi,

I'm hoping to use waffle as a feature flipper for a django 1.6 project, but the latest pypi version, 0.9.2, doesn't seem to work with 1.6.

I've tested the latest master version and it works fine, thanks to this commit, which narrowly missed the last release: https://github.com/jsocol/django-waffle/commit/e23ac27d8b929580b4af4e8867d76e7d449b7d52

Would you be able to push a new version that includes this fix?

Thanks,
Mat

**Comment by jsocol** [comment]
Travis-CI seems to be having some backlog issues, but I'm just waiting on that.

**Comment by jsocol** [comment]
v0.10: https://pypi.python.org/pypi/django-waffle/0.10

Needed a minor version bump because there are backwards incompatible changes in wafflejs.

**Comment by MatMoore** [comment]
I'm late replying, but thanks for this, the new version works fine.
