### ISSUE TITLE
master and 0.10 not working with custom user model

### ISSUE THREAD

**Issue by tijs** [django-waffle/django-waffle#111]
I have just migrated a Django 1.4 installation to 1.5 and while django-waffle seemed to have all the bits in place to support custom user models it does not seem to work. I tried installing 0.10 and the latest master but with both version i get this error when trying to add a Flag:

```
Exception Type: DatabaseError at /tokeh/waffle/flag/add/
Exception Value: column waffle_flag_users.customuser_id does not exist
LINE 1: ..._flag_users"."id", "waffle_flag_users"."flag_id", "waffle_fl...
```

The problem, as far as i can tell, is the initial migration which correctly sets the foreignkey for flag_users but incorrectly freezes the auth.user table.

**Comment by jsocol** [comment]
So specifically the issue is upgrading from Django 1.4 and adding a custom user model? I don't have any issues running 1.5 or 1.6 with 0.10
