### ISSUE TITLE
Changing flag percent of users

### ISSUE THREAD

**Issue by knightcode** [django-waffle/django-waffle#115]
Could you add a timestamp to the cookie value, compare it to the last modified date for a  flag, and, if it's older than the modification timestamp, recompute the flag and reset the cookie.

Bonus points if you could devise a way to only grow the minority, not reshuffle everyone.

**Comment by jsocol** [comment]
"Roll-out mode" is designed to address this: once a flag is on, the cookie persists, but for "off" it's only a session cookie. Does that address the need?

**Comment by jsocol** [comment]
Feel free to re-open if there's more to this.
