### ISSUE TITLE
Support for the Sites framework

### ISSUE THREAD

**Issue by dibell** [django-waffle/django-waffle#116]
Would it be possible to add code to allow different Flags etc. by Site (without requiring Site as in the doc here https://docs.djangoproject.com/en/dev/ref/contrib/sites/) ?

If django-waffle supported the Sites framework it would be useful in more situations. Many other django apps support it (e.g. django-cms).

**Comment by jsocol** [comment]
It's definitely possible, and I think might be a solution to some things I've seen gross hacks for, but this is also exactly the sort of thing the current architecture is already struggling to support. The way I built the checks for flags, "one more check" scales very badly for code organization.

I am going to budget some time this summer to do a mini-sprint on re-organizing Waffle and rewriting the internals, then things like this should be easy to accomplish.

**Comment by dibell** [comment]
I'm going to try to add this in my fork as I'd really like to use waffle but need sites. It's looking OK so far - the main complication is the migration to add Sites isn't simple. If/when I get it into a fit state I'll maybe fire off a pull request?

**Comment by jsocol** [comment]
Closing in favor of the PR #117
