### ISSUE TITLE
Easy way to purge source code of specific flags.

### ISSUE THREAD

**Issue by exit99** [django-waffle/django-waffle#119]
Hello,

Not sure if this is something everybody else is interested in, but does anyone else find it tedious to remove all the custom waffle tags from very large projects?  We're talking hundreds of flags.

I am developing a "purge" function for work that purges your source code of all line of a specific waffle flag.  For example:

> python manage.py flag flag_name -d
> Are you sure you want to remove all references to flag "flag_name"?
>    This is not reversable.  If you are sure use -D
> python manage.py flag flag_name -D

Would this be something other people are interested in having in waffle?

**Comment by jsocol** [comment]
Actually making edits to the source code in a safe way? What defines a reference? Is this going to depend on static analysis? Will it support Django and Jinja2 templates? How does it work? How does it decide which branch to keep (e.g. `if flag_is_active(...): x=y; else: x=z`)?

**Comment by exit99** [comment]
All great questions.

For us we are just pushing to github first, but I agree having a safer included solution would be ideal.  perhaps functionality found references are commented out then the test suite is run before purging.  Open to other ideas for sure.

As of now static analysis, but again, more than open to changes.

For us, we only use one line references.  We are using re to match all the patterns then remove them using a little python script.  Its not exactly fast with large projects, which is a downside.  Perhaps we can think of a better solution?  There is no log for if branching as we only do one liners, but is necessary, of course, for other projects.  

More than open to any and all suggestions, it will do what we need, but I know it can and should be better.

**Comment by jsocol** [comment]
> For us, we only use one line references

I'm not sure I follow, can you give me an example?

This seems exceptionally risky and to be honest I'm really not eager to see it merged in to waffle.

**Comment by exit99** [comment]
So no if else branching.

```
if not waffle.flag_is_active(request, 'flag_name'):
    # do stuff
    return render
# do other stuff
# return redirect
```

On a grander scale I guess it does look risky, and probably is in its current state.  
Thank you for your honesty.  That's why I asked to see if anyone was interested. 

If you change your mind or need anything else merged that you don't feel like tackling let me know, and I would be happy to help.
