### ISSUE TITLE
A way to get django users with active feature flags.

### ISSUE THREAD

**Issue by exit99** [django-waffle/django-waffle#120]
Hello again,

Not sure if this is something you @jsocol or others are interested in, but I have created a way to get a query of users who have had their flag set to true in roll out mode.

Sometimes you need a way to query only the user with specific feature flags, whether it be for sending an email, or modifying models with foreign key relationships to the user.  There is no way to do it without rolling your own.

So, I created a custom list field on the flag model to store user primary keys that is updated by a post_request middleware method.  These then can be accessed easily to get the users, check against foreign keys, etc.  

Is this something anybody else would be interested in having?

**Comment by jsocol** [comment]
So every flag would have a field that could have tens or hundreds of thousands of integers listed in it? I get the need, but that's not really an OK way to do it. Especially since roll-out mode doesn't actually have anything to do with user IDs (it just switches "off" cookies to session cookies).

**Comment by exit99** [comment]
What do you think would be a better way to go about doing it?  I am always up for improving.

**Comment by jsocol** [comment]
When it's tied to users, you can use flag.users or flag.groups directly. When it's tied to cookies, there is no mapping to users. Other settings work are _may_ be tied to users (flag.superusers, flag.staff, flag.authenticated are all, when we add UA and IP those are not). If we successfully add more customizability those may or may not have anything to do with users.

So this, unfortunately, is kind of an ill-formed request, it just doesn't necessarily have an answer.

I would recommend using two groups, an On group and an Off group (maybe with a Sample, or some other logic, to assign people to one or the other) and then tying the flag to the group.
