### ISSUE TITLE
Should Waffle auto discover request?

### ISSUE THREAD

**Issue by leonsas** [django-waffle/django-waffle#121]
Just started using waffle, made sure my requests template processors is there and the waffle middleware. When I try to use a flag in a [Django] template I'm getting:

```
.....
File "/home/vagrant/hypnos-venv/local/lib/python2.7/site-packages/waffle/templatetags/waffle_tags.py" in render
  36.         if self.condition(context.get('request', None), name):
File "/home/vagrant/hypnos-venv/local/lib/python2.7/site-packages/waffle/__init__.py" in flag_is_active
  78.     user = request.user

Exception Type: AttributeError at /surveys/coach
Exception Value: 'NoneType' object has no attribute 'user'
```

I was expecting waffle's middleware to auto-discover the current request and add it to the context.
I easily solved this by adding the request to my template context:

```
def foo(request):
    # my view code
    context['request'] = request
    return render_to_response('template_name', context)
```

Is this expected usage? If it is, I couldn't find it on the docs.

Relevant if this is the expected usage:
When this happens, it fails pretty loudly, so perhaps waffle template tag errors should fail silently instead of crashing the whole thing? The use case is that the waffle tags are in a base template that is extended by templates used in a few other views, so if I forget to add `request` to the context of any view, it will crash the entire app.

For the record:

```
Django==1.6.5
django-waffle==0.10
```

**Comment by jsocol** [comment]
As [it says in the install docs](http://waffle.readthedocs.org/en/latest/installation.html), you need to turn on the [`django.core.context_processors.request`](https://docs.djangoproject.com/en/dev/ref/templates/api/#django-core-context-processors-request) context processor, that is the correct, and simple, solution. Waffle can't "autodiscover" request if it isn't in the template context (waffle actually does "autodiscover" it by pulling it directly out of the template context and not requiring you to pass it in as an argument).

**Comment by leonsas** [comment]
Sorry for not making it clear, but I meant that I did turn on the `django.core.context_processors.request`, and I still need to pass the `request` object manually to my context on every view.

Unless I manually pass the `request` object on the context, I get a `'NoneType' object has no attribute 'user'` when Waffle tries to access the user object from the not-yet-passed request.

Some of my settings:

```
TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_processors.auth',
    'django.core.context_processors.debug',
    'django.core.context_processors.i18n',
    'django.core.context_processors.media',
    'django.core.context_processors.static',
    'django.core.context_processors.request',
    'django.contrib.messages.context_processors.messages',
)

...

MIDDLEWARE_CLASSES = (
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'waffle.middleware.WaffleMiddleware',
)
```

**Comment by jsocol** [comment]
I can't tell from your example, but you need to make sure you're passing a [`RequestContext`](https://docs.djangoproject.com/en/dev/ref/templates/api/#django.template.RequestContext) instance, and not a dict (see the _note_ section below the class description) to `render_to_response`. You can also use the [`render`](https://docs.djangoproject.com/en/dev/topics/http/shortcuts/#django.shortcuts.render) shortcut instead of `render_to_request`.

**Comment by leonsas** [comment]
That was it. I was not passing a RequestContext instance. I think that
should be somewhere in the docs, as some people (including me) don't pass
RequestContexts on every way, and it's easy to miss.
