### ISSUE TITLE
Setting to select a cache

### ISSUE THREAD

**Issue by leonsas** [django-waffle/django-waffle#122]
I think it'd be useful to have a setting to determine which cache Waffle should use.

Of course, an optional setting which would default to 'DEFAULT'. I've seen many people using multiple caches, and for Waffle flags I much rather just use local memory than hit my redis cache.

Thoughts?

**Comment by jsocol** [comment]
:+1:

**Comment by leonsas** [comment]
I'm busy this week, but will try to get some tests up by the end of the week. 
I've been using it in prod and seems to Just Work.

**Comment by jsocol** [comment]
Closing in favor of the PR: #123
