### ISSUE TITLE
Refactor tox.ini

### ISSUE THREAD

**Issue by asyncee** [django-waffle/django-waffle#127]
1. You can optimize tox.ini by using new config format:

http://tox.readthedocs.org/en/latest/config-v2.html#example-generating-and-selecting-variants

for example:

```
envlist = {py26,py27,py32,py33,py34}-django{1.4,1.5,1.6,1.7}
```

So you can delete all your other entires and make the file short and simple.
1. You are testing against django1.7c but not already released django1.7.

**Comment by jezdez** [comment]
This can be closed as it was done in 1a24a2ab9ab6311e0acb64707695feaab18c82c3.
