### ISSUE TITLE
Flag a feature by date-time

### ISSUE THREAD

**Issue by groovecoder** [django-waffle/django-waffle#130]
Add ability to activate a Flag by date & time. e.g., something like:

```
from datetime import datetime

Flag.objects.create(begin=datetime(2015, 04, 01, 0, 0, 0), until=datetime(2015, 04, 01, 23, 59, 59))
```

**Comment by jsocol** [comment]
I really don't see ever supporting this in core. If the core rewrite happens the way I want it to, it should be possible via extension, but this is a "set and forget and get paged at midnight" footgun.
