### ISSUE TITLE
Documentation link to the mock library 404s

### ISSUE THREAD

**Issue by Sveder** [django-waffle/django-waffle#136]
http://waffle.readthedocs.org/en/latest/testing-waffles.html#mocking-flag-is-active section has a link to two mocking libraries. The one for mock doesn't work, and leads to a 404 page.
Instead of pointing to:
https://code.google.com/mock/
it should point to:
http://www.voidspace.org.uk/python/mock/

**Comment by jsocol** [comment]
cf6e1f7c31973337f152c0973735aeb716a2dbac
