### ISSUE TITLE
No waffle/templates/waffle/waffle.js in pypi version

### ISSUE THREAD

**Issue by piotrkilczuk** [django-waffle/django-waffle#14]
http://pypi.python.org/packages/source/d/django-waffle/django-waffle-0.7.3.tar.gz#md5=abbcc15c3590d75b8fbccab4c0d7e8da

Even though it's in the git repo, there is no waffle.js in the pypi tarball.

That results in TemplateDoesNotExist at /waffle.js error being thrown when trying to access your waffle JS.

**Comment by piotrkilczuk** [comment]
Running sdist for 0.7.3 seems to add the missing file correctly, maybe it's worth bumping the version to 0.7.4 and reuploading to pypi?

**Comment by jsocol** [comment]
I had to add it to the manifest to get it to include it. Should be in 0.7.4 now.

**Comment by piotrkilczuk** [comment]
installed like a charm. Thanks :)
