### ISSUE TITLE
Regression: @override_setting('WAFFLE_SWITCH_DEFAULT=True') broken by recent commit

### ISSUE THREAD

**Issue by hwkns** [django-waffle/django-waffle#146]
I have a test that uses this syntax to ensure a waffle switch is set:

```
@override_setting('WAFFLE_SWITCH_DEFAULT=True')
def test_thing(self):
    ...
```

After upgrading to `django-waffle` 0.10.1, this test failed, so I started installing specific commits and running the test again.  Before https://github.com/jsocol/django-waffle/commit/d73293cb2b6f84798e0ba1edd9328b218221834e the test passes, but on and after this commit, the test fails.

**Comment by jsocol** [comment]
Try it against master. 7da872b69791c28c86f92516865a1500514d9ce9 specifically re-overhauls how settings work to fix `@override_settings`.

**Comment by jsocol** [comment]
Please reopen this if the problem persists on master. It shouldn't.

**Comment by hwkns** [comment]
Master works, sorry for the false alarm.  Thanks, @jsocol !

**Comment by hwkns** [comment]
Any chance this fix could get a PyPI release?

**Comment by jsocol** [comment]
No worries! That will be in 0.10.2 or 0.11, depending on how I break up those releases. 0.10.2 is blocked on some caching troubles I ran into that really, really need resolving.
