### ISSUE TITLE
WaffleNode.child_nodelists isn't set correctly

### ISSUE THREAD

**Issue by jmbowman** [django-waffle/django-waffle#148]
The Django template engine's `Node` class uses a `child_nodelists` property to list all properties containing lists of nodes found inside the current one.  This is used by the `get_nodes_by_type()` method, and as of django_compressor 1.4 is also used to find all compressed static asset nodes in a template.  (Version 1.3 was hardcoded to look for the special case of `nodelist_true` and `nodelist_false` properties, which happened to work for the waffle tags but didn't for other common ones.)  I stumbled across this because django_compressor 1.4 now fails to find compress tags inside waffle tags, which causes problems when using offline compression.

This can be resolved by adding `child_nodelists = ('nodelist_true', 'nodelist_false')` to the `WaffleNode` class, and the test suite still passes when this is done.  This matches the behavior of Django's [IfEqualNode](https://github.com/django/django/blob/master/django/template/defaulttags.py#L282).

**Comment by jsocol** [comment]
This is getting a little out of my depth (I don't generally use Django templates and haven't used django_compressor in years) but I'd be very happy to see a test case that we can run without needing django_compressor, or even just a pull req adding this and a link to some kind of docs as to what it is.

**Comment by jmbowman** [comment]
Sure, I can create a PR for it.  The django_compressor problem is a side effect, I should be able to create a good regression test just based on `Node.get_nodes_by_type()`.

**Comment by jsocol** [comment]
Thanks for the fixes!
