### ISSUE TITLE
know how old a flag is so you can clean up old ones

### ISSUE THREAD

**Issue by kumar303** [django-waffle/django-waffle#15]
If the waffle_flag table had a created timestamp column then we could tell how old a flag is.  This would help to identify any flag code that can be deleted since they would no longer need to be disabled.

I'm envisioning using waffle more as an ephemeral way to roll out new code (for QA and for safety), not really as a way to turn features on and off.

**Comment by jsocol** [comment]
The idea is and was to roll out new features, then remove the flag, though I can see more long-lived flags having value on expensive features, or features that may depend on services that can go down (where a health-check won't work).

Should be easy. Needs a South migration to go with it.

**Comment by jsocol** [comment]
775d4b003e96fdac91728b8ceffdc536fb9acd19 and 5eec513444db1ece108d4372949d08da50644306
