### ISSUE TITLE
Allow checking flag_is_active without a request

### ISSUE THREAD

**Issue by joeyespo** [django-waffle/django-waffle#154]
I'm using both Feature Toggles and Business Toggles, but storing Features Toggles in the environment instead of the database. I'm exposing all feature checks on the `User` model because everything is either "everywhere" or "per-user", and also because DRF can serialize the list of enabled features for the client this way.

Is there any way to get a user-aware `flag_is_active`? The request stuff isn't important because our Django backend is just an API. There's no need for us to use the URL parameters.

I understand that some of the flags are stored as cookies instead of on the User table, so I suppose this issue is asking for a way to store per-user toggles on the `User` model instead of a request.

What do you think?

**Comment by jsocol** [comment]
Flags _can_ be [tied directly to a user or a group](http://waffle.readthedocs.org/en/latest/types/flag.html#flag-attributes), without using cookies (cookies are only used for dice roles) or query parameters (which are really only used for various kinds of testing).

If there's some authentication backend that attaches a current user as `request.user`, you can just use the request as is. If not, it shouldn't be very difficult to create a fake one and add the current user to it, e.g.:

``` python
from django.test import RequestFactory
rf = RequestFactory()
class MyAPIView(APIView):
    def get(self, request, ...):
        user = get_the_current_user_somehow()
        fake_req = rf.get('/')
        fake_req.user = user
        if flag_is_active(fake_req, 'my-flag'):
```

User<->Flag (or Group<->Flag) is just a normal ManyToMany field, so adding a user to a flag is just:

``` python
flag = Flag.objects.get('my-flag')
user = User.objects.get(pk=123)
flag.user_set.add(user)
```

**Comment by joeyespo** [comment]
Yeah, that's what I meant. To be able to call `flag_is_active` _without_ some kind of `fake_req`. Especially since the information is on the tables and isn't actually tied to the request (except for dice rolls). One possibility would be to have `flag_is_active` accept both request and user instances.

The fact that you can make a `fake_req` does help though.

Thanks for the reply. I especially appreciate the code :-)
