### ISSUE TITLE
Add Ability to check a condition outside of a request

### ISSUE THREAD

**Issue by issackelly** [django-waffle/django-waffle#155]
Many conditions are applicable outside a request, like percentages, user groups, user languages, etc. It would be great if there was a way to check a flag from a model method.

**Comment by fdemmer** [comment]
why don't you use a switch for that?

**Comment by jsocol** [comment]
If you really want to fake a request outside a request, `RequestFactory().get('/')` is a good way to do it:

``` python
def my_offline_function():
    user = get_user_somehow()
    req = RequestFactory().get('/')
    req.user = user
    if flag_is_active(req, 'some_flag'):
        pass
```
