### ISSUE TITLE
Documentation says WAFFLE_SECURE default False code says True

### ISSUE THREAD

**Issue by iXioN** [django-waffle/django-waffle#157]
The documentation explicitly says that the WAFFLE_SECURE as a default value to false

http://waffle.readthedocs.org/en/v0.10.1/usage.html#global-settings

The code set it to True by default
https://github.com/jsocol/django-waffle/blob/master/waffle/defaults.py

moreover when I set the secure to True (like default), the cookie seems not written (with django 1.7.7)

**Comment by jsocol** [comment]
Those docs are the v0.10.1 (the latest released version). The [latest version of the docs](http://waffle.readthedocs.org/en/latest/starting/configuring.html) reflects the change in the default.

Do you have response headers showing the cookie is not set? Remember that if you set `WAFFLE_SECURE = True` and are running the dev server over HTTP, cookies will be _written_ in responses, but the browser won't send them back.

**Comment by iXioN** [comment]
ok my bad about the doc version, 
sorry
