### ISSUE TITLE
uncache code is using the incorrect call

### ISSUE THREAD

**Issue by dibell** [django-waffle/django-waffle#158]
The uncache code is doing cache.set('name', None). This is specifically recommended against in the django docs. 

> We advise against storing the literal value None in the cache, because you won’t be able to distinguish between your stored None value and a cache miss signified by a return value of None.

It is causing strange behaviour in our system where the expected flag or switch value is not being returned under certain circumstances (e.g. in the unit tests where requests and updates happen very quickly)

The main unit tests are all passing but the override ones are not. I don't have sufficient understanding of what this is intended to do to fix them.  Shouldn't the update called by the override fire the uncache signal? This does not seem to be happening.

**Comment by dibell** [comment]
Further to this I have changed the update functions in waffle/testutils.py to use self.obj.save() and the tests pass but I don't know the rationale behind the original code which was doing a filter and update.

**Comment by sam-at-work** [comment]
I believe I have found the same issues you are having. I have done my best to explain the causes and fixes in the following 2 issues:
[https://github.com/jsocol/django-waffle/issues/162](https://github.com/jsocol/django-waffle/issues/162)
[https://github.com/jsocol/django-waffle/issues/163](https://github.com/jsocol/django-waffle/issues/163)

I have also applied the fixes mentioned in the above issues on our own [fork of Waffle](https://github.com/festicket/django-waffle).

**Comment by jsocol** [comment]
The whole cache system is undergoing an overhaul, see #137. I don't really have an ETA, but I can say that my life is a lot less crazy in the next month than the last month.
