### ISSUE TITLE
Caching bug in _generate_waffle_js view identified and fixed in fork

### ISSUE THREAD

**Issue by sam-at-work** [django-waffle/django-waffle#162]
The caching of ALL_FLAGS/ALL_SWITCHES/ALL_SAMPLES in the _generate_waffle_js view is broken.

These tests from our fork expose the issue.
[django-waffle/waffle/tests/test_cache.py](https://github.com/festicket/django-waffle/blob/master/waffle/tests/test_cache.py)

The issue is caused by the combination of uncaching the models by setting the value to `None` instead of using `cache.delete_many`, and using `cache.add` instead of `cache.set` in the `_generate_waffle_js` view (as is done in the method waffle/views.py:17).

When calling the uncached method, if values are set to `None`, the key remains in the cache. Since the key remains in the cache after calling uncache, calling `cache.add` to add new items to the cache has no effect.

`To add a key only if it doesn’t already exist, use the add() method. It takes the same parameters as set(), but it will not attempt to update the cache if the key specified is already present`

By using `cache.set` instead of `cache.add` in the view will fix the issue.
Also using `cache.delete_many`, instead of `cache.set('key', None)` will also fix the issue.

**Note that fixing the caching will cause issue will identify another issue with the testutils "override_" methods. I will create a separate issue for this.**

I have made all these changes in the [master branch of our fork](https://github.com/festicket/django-waffle). Let me know if you would like me to make Pull Request for them.

**Comment by jsocol** [comment]
This should be fixed by #211
