### ISSUE TITLE
support for django-jinja

### ISSUE THREAD

**Issue by willkg** [django-waffle/django-waffle#166]
A bunch of Mozilla projects (Input, SUMO and possibly others) are switching to django-jinja as we switch to Django 1.8 and dropping jingo and friends. jingo never really caught on. I suspect that django-jinja has a higher likelihood of being the go-to jinja lib for providing more than the basics Django 1.8 provides.

As such, it'd be nice if django-waffle supported django-jinja out of the box.

Does this sound like something we want to do?

If it is something that sounds good, I can create a `django-waffle/waffle/templatetags/jinja_waffletags.py` file and put the code in there. Other names are fine. It'd do nothing if `django-jinja` isn't installed and do what `helpers.py` is doing now if it is.

**Comment by jsocol** [comment]
:+1: go for it, sounds like a plan to me

**Comment by jsocol** [comment]
fixed in #180, though via a different approach
