### ISSUE TITLE
Cache flag_values and sample_values for _generate_waffle_js

### ISSUE THREAD

**Issue by groovecoder** [django-waffle/django-waffle#170]
May need to do https://github.com/jsocol/django-waffle/issues/162 first?

Calling `flag_is_active` and `sample_is_active` inside the list comprehension for every flag and sample starts to add up when there are a number of flags and samples to process. (73% of time spent in `_generate_waffle_js`)

Caching the `flag_values` and `sample_values` should help short-circuit that logic and make it perform better.

**Comment by mwarkentin** [comment]
There was some discussion about this in #142 as well.
