### ISSUE TITLE
Tests failing with Django==1.8.4

### ISSUE THREAD

**Issue by kew-l** [django-waffle/django-waffle#172]
All with:
ImportError: cannot import name get_standard_processors

7 matches for "ERROR" in buffer: _shell_
     53:ERROR: test_django_tags (waffle.tests.test_templates.WaffleTemplateTests)
     89:ERROR: test_jingo_tags (waffle.tests.test_templates.WaffleTemplateTests)
    103:ERROR: test_no_request_context (waffle.tests.test_templates.WaffleTemplateTests)
    138:ERROR: test_flush_all_flags (waffle.tests.test_views.WaffleViewTests)
    187:ERROR: test_flush_all_samples (waffle.tests.test_views.WaffleViewTests)
    236:ERROR: test_flush_all_switches (waffle.tests.test_views.WaffleViewTests)
    285:ERROR: test_wafflejs (waffle.tests.test_views.WaffleViewTests)

**Comment by jsocol** [comment]
This is due to an old version of jingo. Master now supports jinja2 via an extension instead of using jingo directly, and the tests use django-jinja with 1.8 to test it.
