### ISSUE TITLE
Optional param on waffle_flag and waffle_switch decorators to redirect to a view

### ISSUE THREAD

**Issue by rodgomes** [django-waffle/django-waffle#173]
Hi, 

What do you think about having an optional parameter on the mentioned decorators to allow a developer to provide a redirect view, instead of throw a Http404 when the flag/switch is not active?

The decorator signature could be something like:

``` python
def waffle_switch(switch_name, redirect_to=None):
```

Where "redirect_to" could be a view name or view function to be used in django.core.urlresolvers.reverse  

Is this useful to anyone else besides me?

**Comment by jsocol** [comment]
Fixed in #174
