### ISSUE TITLE
Upgrading from django 1.6 to 1.8 fails in migration

### ISSUE THREAD

**Issue by mwaaas** [django-waffle/django-waffle#177]
psycopg2.ProgrammingError: relation "waffle_flag" already exists

**Comment by willkg** [comment]
Can you be more specific? What was the full traceback? What version of django-waffle were you using? What steps did you perform when upgrading from Django 1.6 to 1.8?

**Comment by mwaaas** [comment]
was using django1.6 then decide to upgrade to django1.8 so the first thing that failed was migration 

I changed  the SOUTH_MIGRATION_MODULES to MIGRATION_MODULE a variable defined in settings.py file. 

Now am getting "django.db.utils.ProgrammingError: relation "auth_group" does not exist when I run tests

**Comment by jsocol** [comment]
@mwaaas It sounds like you had already created the tables with South and now it tried to apply the Django migrations, which start by creating the tables.
- Don't rename the `SOUTH_MIGRATION_MODULES` setting. The migrations in `waffle.south_migrations` are not compatible with Django 1.7's built-in migrations, which live in `waffle.migrations`.
- You should run `migrate waffle --fake-initial` (or just `--fake`) to mark the migrations as already applied. Django doesn't yet have the history in its own migrations table, so it just needs to know that those tables already exist.

**Comment by jsocol** [comment]
Please feel free to re-open this if this is still and issue and `--fake-initial` didn't fix it.

**Comment by mwaaas** [comment]
it fixed thanks @jsocol
