### ISSUE TITLE
Waffle should work with stateless (non-DB backed) websites

### ISSUE THREAD

**Issue by ntoll** [django-waffle/django-waffle#188]
I'm working on a website for a client that sits on top of APIs rather than a database. Therefore, it is "stateless" in that we're merely a human-facing shim over the APIs rather than a "proper" website with a swanky database back-end. This is as much for the client's organisation / technical reasons as it is for scalability and simplicity's sake.

We want to be able to use Waffle for feature flagging. I've had to update Waffle in order to meet my client's requirements and have submitted a PR here:

https://github.com/jsocol/django-waffle/pull/187

YMMV. I'm not precious about my code and welcome comments, constructive critique and ideas!

**Comment by jsocol** [comment]
Let's just discuss on #187, since it's already open.
