### ISSUE TITLE
(Maybe) add some syntatic sugar

### ISSUE THREAD

**Issue by jsocol** [django-waffle/django-waffle#19]
Basically:

``` html
<div class="user-info {% if waffle.flag('foo') %}beta{% endif %}">{# This is really long #}
<div class="user-info {{ waffle.something('foo', 'beta') }}">{# Sugar, but kind of nice. #}
```

Would want 3 `something`s, for Flags, Switches and Samples. Maybe it can just be a second, optional argument? That would be fancy!

**Comment by jsocol** [comment]
Think I figured out why the test fails--cache--and I can fix and finish this up!

**Comment by davedash** [comment]
This syntax is a bit off, because I think of `dict.get` in which case the 2nd argument is a fallback.  But maybe a name can fix this:

```
{{ waffle.if_flag('foo', 'hi world') }}
```

or heck:

```
<a class="{{ waffle.if_flag('es', 'elastic', 'sphinx') }}">
```

just have the else as well.

**Comment by jsocol** [comment]
I like the second version, with the `else` value optional. Thanks, Dave!

**Comment by jsocol** [comment]
Bumping this, it's a nice-to-have but I'd rather have Waffle 0.9.

**Comment by jsocol** [comment]
TBH I don't really care about this anymore. I think `{% if ... %}` is clearer anyway.
