### ISSUE TITLE
Flag not persistent

### ISSUE THREAD

**Issue by wasabigeek** [django-waffle/django-waffle#190]
First – thanks for Django-Waffle! It’s exactly what I wanted.

I’m having a little issue with the Flags using Percent though - the randomised setting does not persist (on refresh, it may change). What could be happening?

Some background:
- Django 1.7
- Using waffle in template, used {% load waffle_tags %} and {% flag "flag_name" %} with a different button being shown depending on the flag setting
- Created flag in admin with all settings default (i.e. empty) except Percent, set to 50
- Go to page and refresh a few times. I expect after the first load the cookie should have been set, but on refreshes the button still sometimes changes
- I can see the Cookie being sent in the Response Header (the value of which changes between True and False on refresh):

![cookie](https://cloud.githubusercontent.com/assets/4256705/12093709/6cab471c-b33f-11e5-9bc7-981c182ce6fb.PNG)

**Comment by jsocol** [comment]
Does the browser send the cookie back on subsequent requests?

**Comment by wasabigeek** [comment]
@jsocol I don't see it being sent in the Request. Am I supposed to do something in the views / settings?
![capture](https://cloud.githubusercontent.com/assets/4256705/12105317/84b1f712-b38e-11e5-871e-a755a1457cbf.PNG)

**Comment by jsocol** [comment]
Are there browser settings that could cause it not to send the cookie back on subsequent requests? Privacy or developer options or addons? If waffle doesn't see the cookie, it will re-roll and the flag state may change. That is correct behavior.

If the browser is sending the cookie on subsequent requests but waffle is not respecting it, that's a bug.

**Comment by wasabigeek** [comment]
Hi @jsocol, so it's a newbie mistake - cookie was set to secure only, but my connection was not over SSL. Do you think it's advisable to set it to send over non-secure (saw there was a setting for it)?

**Comment by jsocol** [comment]
If you don't have SSL set up (for local development or for production) yes, you'll need to adjust the relevant setting.
