### ISSUE TITLE
New Release to fix Py3 compaibility issues

### ISSUE THREAD

**Issue by techdragon** [django-waffle/django-waffle#192]
@jsocol would it be possible to release a version containing the fixes from #178 ? I'm currently having to manually exclude waffle every time I create my migrations. I'm probably not the only one, so a new release to clean up this issue on python 3 would be nice.

**Comment by Chronial** [comment]
@jsocol Any chance for this? Is there something I can do to support you here?

**Comment by techdragon** [comment]
#198 could be related to this.

**Comment by clintonb** [comment]
@jsocol can we get an updated PyPI package, please? The last release was over seven months ago.

**Comment by jsocol** [comment]
Working on this today

**Comment by jsocol** [comment]
https://pypi.python.org/pypi/django-waffle/0.11.1 0.11.1 is out! Tests run on all the same versions as 0.11, as well as 1.9. 0.12 will drop support for Django <1.8.
