### ISSUE TITLE
Disable flag for individual users

### ISSUE THREAD

**Issue by dan-passaro** [django-waffle/django-waffle#194]
We've been using this library to gradually roll out a new version of a complex feature on our app and it's been great. So far we have it rolled out to 20% of our clients and the process was very smooth.

For the most part our feature seems to be working well, but there are a few power users we have where our feature isn't 100% up to snuff yet. I would love to be able to disable the flag for them, which will let them use the old version, until we address the shortcomings in the new version.

However this doesn't seem possible with django-waffle (at least version 0.11). We can opt users _in_, which is nice. We tried using the "testing" mode but that seemed to disable the feature by default. Additionally it requires a querystring, etc. which is a bit more technical than I'd prefer (our clients are power users of our app but not necessarily power users of tech :) ).

Is there any way to disable flags based on a user's ID? If not, is there any interest in a pull request that includes such a feature?

Also, thanks for the great work on this library!

**Comment by jsocol** [comment]
It's not possible right now, and it's a complication that I'm kind of disinclined to take on. It makes flags conceptually much more complicated. And it should really have a parallel for groups. So if a user is in two groups or is named twice, what happens? "Why isn't the flag acting how I expect it to?" Etc.

I think as Waffle approaches 1.0, there are already planned changes—in this case moving logic into `Flag.is_active()` and building abstract base classes that could be extended—that will make it easier to extend and build custom logic like this.
