### ISSUE TITLE
Turning flags on for testing should be easier

### ISSUE THREAD

**Issue by kumar303** [django-waffle/django-waffle#21]
Right now for running a test with a flag you have to do one of the following:

```
with patch.dict(jingo.env.globals['waffle'], {'flag': lambda x: True}):
    # get a view using {% if waffle.flag(...) %}
```

or

```
with patch('waffle.flag_is_active') as flag:
    flag.return_value = True
    # get a view using if waffle.flag_is_active(...)
```

(and the same for switches)

These are both cumbersome.  The first one also has a major problem in that the jingo.env is created lazily and the waffle key won't exist so you have to do `import waffle.helpers` beforehand.

Am I missing an easier way?

Another minor problem is that the test code in no way references the name of the flag or switch so you can't find/replace it later on when removing the flag.

I don't have a solution in mind but I wanted to submit this so I don't forget to think about it.  Maybe there needs to be something built into waffle specifically for testing.  I know Andy McKay has taken some stabs at solving this too.

**Comment by jsocol** [comment]
@andymckay I forgot what your solution was to this, was it `@mock.patch.dict()`?

**Comment by andymckay** [comment]
A try was https://github.com/andymckay/django-waffle/commit/b0550cb9ce1e6207769a7f3f1b2441c1f8a68ddd but that needs work. But this all feels like workarounds, wondering if we can register the helpers differently to prevent this (no idea what that would be, just thinking).

**Comment by andymckay** [comment]
Yep, what kumar303 has at the top.

**Comment by kumar303** [comment]
It is somewhat of a jingo problem (but would probably apply to jinja as well) in that the there are leaky refs to the helpers in the jingo registry and these are not cleared between tests since they are filled at import time.

**Comment by kumar303** [comment]
Well, huh.  I took a closer look at waffle.helpers and now this solution is working for me (instead of patching the jingo dict):

```
@patch('waffle.helpers.flag_is_active')
def test(self, flag):
    flag.return_value = True
    # the view with {% if waffle.flag(...) %}
```

Maybe we just add that to the docs and close the issue :)

**Comment by jsocol** [comment]
Another option is to create the flag in the test. I actually do that in almost all the Waffle tests--create the flag, set it's value to whatever I want, and go from there. It uses the fallback value iff there's no flag.

**Comment by jsocol** [comment]
04b50bd529b12f83c8b44468c86ceceb28ba8aca

Added some documentation. Should cover Jinja and Django template helpers.
