### ISSUE TITLE
Multi tenancy for feature flipping

### ISSUE THREAD

**Issue by FlogFr** [django-waffle/django-waffle#217]
Hey,

Is there a clean way to have a FK from the "Flag" and other to a `SITE_MODEL` in order to be able to do feature flipping for a specific site.

I'll try to fork the project and open a PR, with an app config parameterization.

What do you think about it?

**Comment by cleder** [comment]
see https://github.com/jsocol/django-waffle/pull/117 discussion

**Comment by FlogFr** [comment]
thanks and sorry for the duplicate post. Closing this issue.
