### ISSUE TITLE
can't add group to flags using manage.py waffle_flag

### ISSUE THREAD

**Issue by hyunwoona** [django-waffle/django-waffle#222]
I am trying to add or remove groups to a waffle flag.
I see I can manage all flag attributes (in http://waffle.readthedocs.io/en/latest/types/flag.html page.) from manage.py, except for Groups and Users.
I believe --groups, or --users option should be there, but it's missing?
I can add groups on Django shell by importing waffle.models.Flag, but I want to do it using manage.py.
How can I do this?
Also, can I do this in Django admin page?
Thanks.

**Comment by jsocol** [comment]
You can definitely do this via the admin page.

I'm going to be honest, I've never really used the management commands. Other folks very much wanted to add them, but they're not very well maintained or tested. I'm definitely open to PRs that add features to them (or maybe they need to spin off into their own package). It would be nice if those PRs had tests. But I'm not likely to get to fixing issues or adding features in the management commands.

**Comment by hyunwoona** [comment]
Thank you.

I'm not using the admin page, and I think I'll just create a simple page that does it using waffle.models.Flag.
Would you say adding target users to groups and then tying groups to flags is a good way to add users to waffle flag, or tie users directly to flags is a better way? Is there any other way to do this other than these two?

**Comment by jsocol** [comment]
It really depends on what you're going for and how/if you're already using groups to manage users.

**Comment by jsocol** [comment]
Fixed by #252!
