### ISSUE TITLE
override on querystring not working with Selenium?

### ISSUE THREAD

**Issue by wasabigeek** [django-waffle/django-waffle#229]
I was trying to use the [querystring override](https://waffle.readthedocs.io/en/v0.11/testing/automated.html#external-test-suites) but it doesn't seem to be working.

On local with `manage.py runserver`, using the flag in the querystring works. However, once selenium-python kicks off the test, the flag doesn't work.

I'm using `StaticLiveServerTestCase` + FireFox ESR + Django 1.9.6 and on Windows:

Test:

```
def test_pricelist_funnel(self):
        test_url = '{0}/?flag=1'.format(self.live_server_url)
        self.browser.get(test_url )
```

View:

```
url = reverse('app:view1')
if flag_is_active(request, 'flag'):
    url = reverse('app:view2')
```

Template:

```
<a href="{{ url }}">
       view pricelist
</a>
```

On local, the url is `reverse('app:view2')`, but when running with Selenium, it's `reverse('app:view1')`

**Comment by jsocol** [comment]
Have you turned on [`WAFFLE_OVERRIDE`](https://waffle.readthedocs.io/en/v0.11/starting/configuring.html#starting-configuring) in the test settings? It is off by default, since it's really only intended to be used in test envs.

**Comment by jsocol** [comment]
Closing this out as unanswered, but please re-open if you're still having an issue!
