### ISSUE TITLE
WAFFLE_SWITCH_DEFAULT and WAFFLE_FLAG_DEFAULT have no effect

### ISSUE THREAD

**Issue by kumar303** [django-waffle/django-waffle#23]
```
WAFFLE_FLAG_DEFAULT = True
```

...in settings does not make this return True as expected:

```
waffle.flag_is_active('non-existant')
```

The same applies to template helpers and switches.

**Comment by jsocol** [comment]
I'm a little confused, because I do have tests that cover this, and I can't reproduce on the shell.

**Comment by kumar303** [comment]
Oh really? Maybe it was fixed. We're on an old revision from April 20th and I can still reproduce it in manage.py shell. I tried to upgrade "real quick" but our DB needs a migration; I didn't get that far so I couldn't test the latest code.

**Comment by jsocol** [comment]
d23e00db69580289b273c816e09a5180afa8daed is pre-created/modified schema changes (v0.7.6 on PyPI). I'm curious what version you're on, and if there were other schema changes since then. /me looks.

**Comment by jsocol** [comment]
There are [tests](https://github.com/jsocol/django-waffle/blob/master/waffle/tests/test_waffle.py#L227) [covering](https://github.com/jsocol/django-waffle/blob/master/waffle/tests/test_waffle.py#L311) [these](https://github.com/jsocol/django-waffle/blob/master/waffle/tests/test_waffle.py#L339)  that pass, so unless someone can reproduce, I'm closing this as WFM.

**Comment by jameskeane** [comment]
Shouldn't WAFFLE_SWITCH_DEFAULT and WAFFLE_FLAG_DEFAULT, change the wafflejs javascript default behaviour to return true if the flag is not in the dict?

Currently, it does not seem to do this.

Opened #72 to address this.
