### ISSUE TITLE
What is the state of this project?

### ISSUE THREAD

**Issue by clintonb** [django-waffle/django-waffle#245]
Is this project still maintained? If so, who are the maintainers responsible for merging code and releasing to PyPI?

If this package is not maintained, can the following steps be taken?

1. Now: Update the README to reflect the state of the project, and request new maintainers.
2. Later: Transfer ownership of the project (including the PyPI package) to new maintainers.
3. Later: Update the README of this repo to point to the location of the new repo.

**Comment by clintonb** [comment]
@jsocol would you mind commenting?

**Comment by jsocol** [comment]
I started a new issue linked here but the tl;dr is that it's ostensibly maintained but practically not a high priority for me lately and I need help. If you're willing, mind commenting on #246?

**Comment by clintonb** [comment]
See #246.
