### ISSUE TITLE
Call for Maintainer Help

### ISSUE THREAD

**Issue by jsocol** [django-waffle/django-waffle#246]
To answer @clintonb's question in #245—perhaps it's already obvious—this project has not been high on my list lately, due to any number of factors (I don't write a lot of Python day-to-day at the moment, weekends have been nice outside lately, others).

To keep the project alive will need the support of more maintainers. I love to add two or three folks to GitHub and PyPI who

1. use Waffle in their day jobs / active projects;
2. have at least opened a PR, even if I haven't merged it;
3. want to see Waffle improve, hopefully beyond their immediate needs; and
4. care about making open source a welcoming and inclusive space.

If you'd like to help out (I suspect a couple of folks from #245, #243, #241, #226 and other recent issues might be willing, but don't want to assume) please comment here or email me, and let me know your PyPI username.

**Comment by clintonb** [comment]
I am personally interested. My PyPI username is clintonb. I will check to see if @edx is interested in taking some form of ownership.

**Comment by jsocol** [comment]
@clintonb Thanks! I thought you might be but didn't want to volunteer you. Invited to GH and added to PyPI.

**Comment by rlucioni** [comment]
@jsocol I'm also interested. My PyPI username is `rlucioni`. I work with @clintonb at edX and have used Waffle for a few years.

**Comment by ahsan-ul-haq** [comment]
@jsocol I am also interested. My PyPI username is ahsan-ul-haq. I work with @rlucioni and @clintonb at edX and also have been using Waffle for quite some time.

**Comment by Schnouki** [comment]
Hi,

Came her to ask about that so it's great to hear this @jsocol! 

I was also going to suggest something else: if it's OK for you, you could transfer to repo to the [Jazzband](https://github.com/jazzband) org, which would allow all Jazzband contributors to work on Waffle. (More about Jazzband [here](https://jazzband.co/)). They currently maintain big projects such as django-debug-toolbar, django-hosts, django-model-utils, pip-tools, django-pipeline...
But if there are already several people interested, then there's probably no need for that.

Thanks @jsocol and everyone else!

**Comment by clintonb** [comment]
After a cursory glance at the docs for Jazzband, I like the idea. I'll take a closer look later today.

**Comment by clintonb** [comment]
So far I have only seen/heard good things about Jazzband, and no negatives. I like the idea of a community of maintainers.

@jsocol one last request of you: Would you either make me an admin so that I can move the repo to @jazzband, or [join the org](https://jazzband.co/) and move it for us?

**Comment by clintonb** [comment]
@jsocol would you also grant me admin access to the RTD repo?

**Comment by jsocol** [comment]
I've added:
- @clintonb to RTD
- @rlucioni and @ahsan-ul-haq to PyPI and GH as maintainers.

I'm not yet ready to totally hand over ownership of this project to JazzBand or edX. I might be at some point, but not now.

I'm still open to adding more maintainers, so I'm going to leave this open for a while.

**Comment by rlucioni** [comment]
Thanks @jsocol.

**Comment by ahsan-ul-haq** [comment]
Thanks @jsocol
