### ISSUE TITLE
Which version is compatible with Django 1.4

### ISSUE THREAD

**Issue by spapas** [django-waffle/django-waffle#258]
Hello, I have an old application running Django 1.4 which will benefit from django-waffle (yes the application will benefit even more by upgrading to latest django but that's not possible right now because of lack of resources and especially lack of tests in the application). Can you tell me which is the latest version of django-waffle that supports Django 1.4?  

I tried deducing it from the changelog and seems that it probably is version 0.9 or 0.10 but I am not sure which one to use...

Thank you!

**Comment by jsocol** [comment]
You're best bet is to look at the [history of `.travis.yml`](https://github.com/jsocol/django-waffle/commits/master/.travis.yml) to see when it was dropped.

But please remember that both Django 1.4 and whatever version of Waffle that is are *unsupported* and Django in particular will contain known security vulnerabilities that are not patched. Moving to a newer ESR ASAP is an absolutely critical piece of work.

**Comment by spapas** [comment]
Hello @jsocol thanks, I think that travix.yml also confirms that version 0.10 is the last that supports django 1.4. I am fully aware of the implications of using an old django version - it is used is for an internal (enterprise) application so it should be secure enough.
