### ISSUE TITLE
Waffle Switch appears to toggle on/off during page refreshes

### ISSUE THREAD

**Issue by jamesmorgan** [django-waffle/django-waffle#264]
We have implemented a basic waffle switch and have used `waffle_tags` in the html to show/hide a form question. 

What we are experiencing is that when the switch is toggled there is a period of time that when you F5/refresh the page the question shows/hides. My assumption is that something is caching the switch but this seems like odd behaviour. 

Our AWS setup using the same conifg as found here http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-container.html

We have been using the admin screen to toggle the switch on/off. 

We have no custom waffle settings.

Django version : 1.10.1
Waffle version : 12.0

Any ideas?

**Comment by jsocol** [comment]
What kind of cache setting are you using?

**Comment by jamesmorgan** [comment]
These are the two settings which we have tweaked:
```
waffle = Settings(
    WAFFLE_OVERRIDE=False,
    WAFFLE_READ_FROM_WRITE_DB=True
)
```
I have tried changing `WAFFLE_READ_FROM_WRITE_DB` with no change either way

Django uses: `'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'`

**Comment by jsocol** [comment]
Ah, gotcha. I'm guessing you are running multiple processes or multiple servers?

This is one of the properties of `LocMemCache`: it can't be globally expired or flushed, you just need to wait for it to time out.

If you change a switch value on Process A, it will clear _its own_ `LocMemCache` cache, but it doesn't know about and can't clear the cache on Process B. So the different processes end up out of sync until they all expire.

I'd recommend setting up an Elasticache Redis or Memcached instance, creating a new `CACHES` entry, and using that, at least for Waffle flag caches. But anything where you want all the Django processes to agree at the same time will also benefit from a shared cache.

**Comment by jamesmorgan** [comment]
Thanks for the info 👍

**Comment by jsocol** [comment]
Sure thing, hope that helps!
