### ISSUE TITLE
Why this and not X?

### ISSUE THREAD

**Issue by davedash** [django-waffle/django-waffle#27]
waffle hints that there are other feature flippers (there are), so it might be nice to mention why you'd choose waffle (or not choose waffle) over the others

**Comment by riverfr0zen** [comment]
This is the question I came here to ask.

**Comment by tobych** [comment]
http://www.djangopackages.com/grids/g/feature-flip/ has a matrix showing features of the various flippers.

I'm giving Waffle a go, although I'm also co-author of django-feature-flipper.

**Comment by tobych** [comment]
We're happily using Waffle in production now.

**Comment by jsocol** [comment]
cf6e1f7c31973337f152c0973735aeb716a2dbac
