### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mark-adams** [django-waffle/django-waffle#271]
Is there any chance we could get a release containing https://github.com/jsocol/django-waffle/commit/f4d6243d5d2719b1e8f4ba09e3ce3d982fbfa0db ?

Thanks! 😄 

cc: @jsocol

**Comment by clintonb** [comment]
Unless @jsocol objects, I'll release a new version this weekend with everything in this changeset: https://github.com/jsocol/django-waffle/compare/v0.12.0...master. Version number will most likely be 0.13.0 since there is a combination of bug fixes and new functionality.

**Comment by jsocol** [comment]
Agreed, we should get Django 2 support out there

**Comment by kylehg** [comment]
👋 Hi all! I just ran into the the compatibility issues with Django 2.0...is there anything holding up the 0.13 release that I could help with?

**Comment by clintonb** [comment]
@kylehg that's my fault for not making reminder for last weekend. Barring issues, I will have a release out by 10PM PST today.

**Comment by clintonb** [comment]
Sorry for the delay. 0.13.0 is now available!

https://pypi.python.org/pypi/django-waffle/0.13.0

**Comment by kylehg** [comment]
Thank you @clintonb !
