### ISSUE TITLE
Management command to clean up unused waffle switch/flag/samples

### ISSUE THREAD

**Issue by ndibari-sp** [django-waffle/django-waffle#274]
waffle-django library does not have a built-in way to delete unused flags/switches/samples. The goal of this issue is to develop a management command that can be run to delete a list of flags/switches/samples passed to the management command.

For example, a command like `waffle_delete` could take `--flags` as an argument, and the full command `waffle_delete --flags my_flag_1, my_flag_2` would delete the flags name my_flag_1 and my_flag_2 from the database.

**Comment by jsocol** [comment]
Closed by #275, thanks @ndibari-sp!
