### ISSUE TITLE
Customizable Flag's groups model

### ISSUE THREAD

**Issue by hugobessa** [django-waffle/django-waffle#286]
The `auth.Group` model is used often as user's role. Would be good if was possible to customize, through Django settings, the model used in `Flag.groups`. This way it wouldn't be required to use user's role to define whether he access to a feature. In my case I'd like to have a custom `FlagsGroup` (developed in my project scope) instead.

Would like to hear from the official contributors if you think this would be a relevant feature in this lib. I'm available to make a PR really soon.

**Comment by jsocol** [comment]
I think this overlaps with #181, which allows userland definition of flags and their relationships to other models.

**Comment by hugobessa** [comment]
@jsocol is #181 being implemented by someone right now? I saw there's a work in progress PR, but it is closed. I really need to customize this '`FlagsGroup`' behavior in one of my projects, so I'm available to implement this if necessary.
