### ISSUE TITLE
Create mixins for class based views to replace the decorators

### ISSUE THREAD

**Issue by hugobessa** [django-waffle/django-waffle#287]
Create `WaffleFlagViewMixin` and a `WaffleSwitchViewMixin` to use in class based views intead of the available decorators.

**Comment by jsocol** [comment]
Is this different than #92?

**Comment by hugobessa** [comment]
@jsocol sorry, I didn't see this PR :weary:. I've made my own PR for this in my fork with all the tests and everything. I'll add some docs and PR here.
