### ISSUE TITLE
Make it easier to write automatically-removable flag branches

### ISSUE THREAD

**Issue by hugobessa** [django-waffle/django-waffle#288]
To avoid nesting code with if/else when changing logic whether a flag/switch is active or not. 

My proposal is to decorate helper functions with a `waffle_call` decorator and make the braching with a helper function. 

```python
@waffle_callable
def test_func_a(a, b, c):
    return (a, b, c)

@waffle_callable
def test_func_b(a, c):
    return (a, c)

my_return = waffle_switch_call(
    'my_switch', active_callable=test_func_a(1,2,3), inactive_callable=test_func_b(1, 3))

# or

my_return = waffle_flag_call(
    request, 'my_flag', active_callable=test_func_a(1, 2, 3), inactive_callable=test_func_b(1, 3))
```

I think this code style will force the users of the lib of creating more readable and modular code.

But the main objective of this architecture here is to make easier to implement automatic removal of flags in the code base using Abstract Syntax Tree tools like [astroid](https://github.com/PyCQA/astroid).

**Comment by jsocol** [comment]
See discussion on #294
