### ISSUE TITLE
Can't resolve view when decorating DRF viewset with redirect

### ISSUE THREAD

**Issue by martinburchell** [django-waffle/django-waffle#295]
I'm decorating a DRF viewset method like this:

```
from rest_framework.viewsets import ViewSet

class FooViewset(ViewSet):
    @waffle_switch('foo_switch', redirect_to='feature_disabled')
    def create(self, request):
          ...                                 
```

The view looks like this:

```
from rest_framework.response import Response
from rest_framework.decorators import api_view


@api_view(['GET'])
def feature_disabled_view(request):
    return Response({'error': 'This feature has been switched off by the administrator'})

```

The URL looks like this:
`    url(r'^feature_disabled/$', feature_disabled_view, name='feature_disabled'),
`

The problem is that when we try to resolve the URL in `get_response_to_redirect()`, the arguments do not match because args=<rest_framework.request.Request object>.

Am I doing something wrong here or is this a limitation with DRF?

**Comment by clintonb** [comment]
It's not technically an issue with DRF. The decorators are meant to decorate instances of Django's `View` class. `ViewSet.create()` is part of the DRF API, not Django. If you don't mind every endpoint being behind the switch, you can try decorating the `dispatch()` method. Alternatively, ditch the decorator for a simple `if` statement inside `create()`.

**Comment by martinburchell** [comment]
OK understood. Thanks!

**Comment by decentral1se** [comment]
Given that DRF is pretty much the go-to web framework, could we get this re-opened for consideration?

We'd certainly like to be able to decorate our DRF views and I am sure people will run into this.

Is there some reason you wouldn't want this included in the core package @clintonb?

**Comment by clintonb** [comment]
I am open to thoughts on how to implement this cleanly, and in a manner that is better than my proposed approach. This issue was initially closed because a resolution was provided to the requester.

I am a proponent of relatively small packages with a single responsibility, so I am more inclined to use the building blocks/primitives available, and make my own decorator/method.

What is your use case @lwm? How are you solving this problem now? How would you like to solve it?

**Comment by jsocol** [comment]
See also #221

**Comment by clintonb** [comment]
@lwm, let's move this conversation to #221.
