### ISSUE TITLE
the override_switch doesn't clean the cache making fail tests that use the same switch

### ISSUE THREAD

**Issue by ghost** [django-waffle/django-waffle#309]
The latest implementation of Switch.is_active() use a cache.

The override_switch function from testutils doesn't clean this cache in the exit, so if there are two tests over the same switch using different states (active/inactive) the second one to be executed fails as gets the value from the cache with the old value.

This is the code (put there for debugging where the switch is used):
```
from waffle.models import Switch
print("switch name:", 'switch_name1', "active:", switch_is_active('switch_name1'))
switch = Switch.get('switch_name1')
print("requested switch:", switch, ",", switch.pk, ",", switch.is_active())
print("Switch instances:", [(s, s.pk, s.active) for s in Switch.objects.all()])
```
and the output of an execution of a test after other tests that use the same switch.
This fails (because expects to get a True in the switch_is_active):
```
switch name: switch_name1 active: False
requested switch: switch_name1 , 55 , False
Switch instances: [(<Switch: switch_name1>, 64, True)]
```
As you can see, in the database there is a new Switch instance (id=64) with the expected "Active" state, but Switch.get('switch_name1').is_active() returns the value of the instance set up in a previous test (ID=55)

**Comment by clintonb** [comment]
@danhenryten can you submit a PR to fix?

**Comment by chrisguidry** [comment]
Hi @clintonb, I posted a PR for the fix: https://github.com/django-waffle/django-waffle/pull/314

Nice work on making `django-waffle` so easy to hack on.  I was able to get the test suite running and the regression tests written very quickly.  Thanks!
