### ISSUE TITLE
Specify user list for flag using CLI

### ISSUE THREAD

**Issue by acraftydev** [django-waffle/django-waffle#311]
I'm trying to administer a flag using the cli but currently there is no option to specify a list of users only list of groups. I'm looking at waffle/management/commands/waffle_flag.py and can't see any parsing for a user switch?

I'm happy to try and patch it but wanted to make my understanding was correct.

**Comment by clintonb** [comment]
@crafty78, you are correct: there is no support for passing a list of users to that command. Is there a reason you prefer to pass in users rather than use a group? I'm open to updating the command, but I want to better understand your use case.

**Comment by acraftydev** [comment]
Convenience, we often trial features quickly with a couple of individual users before large groups, so being be able to toggle for user rather than having to manage a group is quickest. Also i'm not aware of a built-in django auth admin cli for managing groups (ie creating/adding/removing) and we do our admin via the cli.

**Comment by clintonb** [comment]
Post a PR, and I'll review this weekend.
