### ISSUE TITLE
Hard to see which users and groups a flag is activated for

### ISSUE THREAD

**Issue by PetterS** [django-waffle/django-waffle#313]
The admin panel only shows the primary key (integer) of the users and groups the flag is activated for. It takes a while to determine who they are.

It would be great if the user and group names could be displayed.

**Comment by clintonb** [comment]
@PetterS any interest in creating a PR to fix this?

**Comment by PetterS** [comment]
Sure, maybe over the holiday break.

**Comment by PetterS** [comment]
Made a PR. It is a start, at least.
