### ISSUE TITLE
Global module cache client causes thread safety issues when using Memcached backend.

### ISSUE THREAD

**Issue by Subaku** [django-waffle/django-waffle#319]
Hello,

We recently upgraded to Waffle 0.15.0 and noticed some thread safety issues with how the cache client is being used. We use Memcached and it's known that their client is not thread safe. The general setup we have is a Django site running through Uwsgi and in addition to browsing said site several simultaneous hits to our DRF API which are also handled through Uwsgi. All of these things of course making calls to waffle's "*_is_active" methods. 

One of the many Sentry errors we got that make it fairly obvious:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/1900930/50788244-a88c1a00-126d-11e9-851a-5a51721838dd.png">

To test this I hacked Waffle anywhere the line `cache = get_cache()` was defined at the top of the module which was only in models.py and managers.py. Instead I get the cache client each time it is needed within methods and have let this issue stew over the weekend and the problems have all disappeared.

Is there a design decision behind how the client is referenced?

Thanks!

**Comment by clintonb** [comment]
@Subaku I only recent took over the project, so I cannot speak to whether this was a design decision. Regardless, I agree that this is not ideal. Mind opening a PR with this change?

**Comment by Subaku** [comment]
Sure I'd be happy to. One thing I would love some help on is testing this regression. Do you have any suggestions on where to begin with this sort of test? 

Thanks 😃

**Comment by clintonb** [comment]
@Subaku I've struggled to come up with a decent test case over the past 1-2 hours. I'm willing to merge an untested fix.

**Comment by Subaku** [comment]
I appreciate your attention to this and the effort! I've submitted a fix for it. 

Side question. Would a separate pull request be good to bump the version? I noticed that in the past two releases the version was never bumped and stayed at 0.13.0.

**Comment by clintonb** [comment]
Merged. I'll release 0.15.1 shortly.

**Comment by Subaku** [comment]
Great! Thanks for that :) I'll close this up then.
