### ISSUE TITLE
Switches are not being automatically created

### ISSUE THREAD

**Issue by JerzySpendel** [django-waffle/django-waffle#327]
I have set `WAFFLE_CREATE_MISSING_SAMPLES` to `True` and it simply doesn't work. When I do:
`waffle.switch_is_active(X)` for `X` which is not defined, `X` is not created in the DB.

**Comment by clintonb** [comment]
`WAFFLE_CREATE_MISSING_SAMPLES` will create new `Sample` instances. `waffle.switch_is_active` only checks for `Switch` instances. It seems you want to use the `WAFFLE_CREATE_MISSING_FLAGS` setting. Would you confirm you are using the correct setting?

**Comment by JerzySpendel** [comment]
I meant `WAFFLE_CREATE_MISSING_SWITCHES` of course, but I will double check it. I'm pretty sure I used that variable in my settings.

**Comment by clintonb** [comment]
@JerzySpendel please comment if there is still an issue.
