### ISSUE TITLE
Missing switch records causes a database hit

### ISSUE THREAD

**Issue by adamn** [django-waffle/django-waffle#34]
As a switch user,
I want non-existent switch values to be cached just like existing inactive switches,
So that my database isn't overloaded.

Given a switch_is_active('record_name') is called
When record_name does not exist
Then record_name is cached as inactive in the same way that an actual inactive record would be cached.

Tech  Notes:
- Currently, the status of a switch record is cached - enabling high throughput switch checks without overloading the database.
- However, if the switch record does not exist, a database hit happens every time switch_is_active() is called.
- Instead, the same caching logic should be used as is used for a switch record being inactive.

**Comment by jsocol** [comment]
I think the best option is to cache that it doesn't exist--otherwise changes to settings (WAFFLE_SWITCH_DEFAULT) could cause inconsistent behavior--and that way the save/delete signal handlers will still fix the cache correctly. Make sense, or am I missing something?

**Comment by adamn** [comment]
Great solution. Mixing does not exist and inactive was probably a bad idea
but the important part is that the scenario gets cached.

On Mon, May 14, 2012 at 4:52 PM, James Socol <
reply@reply.github.com

**Comment by jsocol** [comment]
Added to the 0.9 milestone. Hopefully tonight.

**Comment by jsocol** [comment]
@AdamN - Can you take a look at this branch, maybe run your test suite against it? If the strategy works here, it was a small refactor, and I'd like to apply it to Flags and Samples, too.
