### ISSUE TITLE
Update documentation site for 0.17.0

### ISSUE THREAD

**Issue by peteretep** [django-waffle/django-waffle#342]
A new version of django-waffle has been released to pypi - https://pypi.org/project/django-waffle/
The documentation at read the docs is still on version 0.16.0 - https://waffle.readthedocs.io/en/stable/

**Comment by clintonb** [comment]
The latest version of the docs is v0.17.0. I'm looking into why the tag doesn't appear.

**Comment by clintonb** [comment]
Weird. I have to manually rebuild—as mentioned in https://github.com/readthedocs/readthedocs.org/issues/3508 —to trigger the tag refresh. The v0.17.0 tag is now available.
