### ISSUE TITLE
Unnecessary database hits when CREATE_MISSING_SWITCHES is True and the switch does not exist

### ISSUE THREAD

**Issue by vergeev** [django-waffle/django-waffle#343]
## What do I do

I'm calling repeatedly `switch_is_active` without adding the switch to DB. I also have `WAFFLE_CREATE_MISSING_SWITCHES` set to `True`

## What do I expect

I expect that even though I call `switch_is_active` n times, it hits the database only one time.

## What actually happens

`switch_is_active` hits the database every time I call it. 

## Why it happens

Here's the `switch_is_active` method body:

```
def switch_is_active(switch_name):
    from .models import Switch

    switch = Switch.get(sample_name)
    return switch.is_active()
```

If the switch does not exist, method `Switch.get` puts `CACHE_EMPTY` into the cache:

```
try:
   obj = cls.get_from_db(name)
except cls.DoesNotExist:
    cache.add(cache_key, CACHE_EMPTY)
    return cls(name=name)
``` 

And when cache key has the value `CACHE_EMPTY`, it returns an object without primary key:

```
if cached == CACHE_EMPTY:
    return cls(name=name)
``` 

And this is why `is_active` makes superfluous database query:

```
if not self.pk:
    # ...
    if get_setting('CREATE_MISSING_SWITCHES'): 
         Switch.objects.get_or_create(
             name=self.name,
             defaults={
                    'active': get_setting('SWITCH_DEFAULT')
             }
          )
```

## What do I propose

I propose caching the switch value upon calling `get_or_create`.

## Related

- https://github.com/django-waffle/django-waffle/issues/34

---

Let me know if you want me to fix it.

**Comment by clintonb** [comment]
Yes, feel free to post a PR with tests and a fix.
