### ISSUE TITLE
Admin panel quick actions do not show up in the Django admin log

### ISSUE THREAD

**Issue by PetterS** [django-waffle/django-waffle#348]
Quick actions like "Enable selected flags for everyone" do not show up in the Django admin log. If the flag is edited in the normal way, the edit will show up in the history.

**Comment by PetterS** [comment]
We should use `log_action` to do this manually: https://github.com/django/django/blob/90abdba08657db397f1887b94ec1ebdc32783379/django/contrib/admin/models.py#L26

**Comment by PetterS** [comment]
Do this here: https://github.com/django-waffle/django-waffle/blob/ab004b37838b70b4a34153257e1e4c0ea2646f67/waffle/admin.py#L24

**Comment by clintonb** [comment]
@PetterS can you open a pull request with these changes?

**Comment by PetterS** [comment]
Absolutely!
