### ISSUE TITLE
Feature: add category field to flag / switch models

### ISSUE THREAD

**Issue by hugorodgerbrown** [django-waffle/django-waffle#365]
We use waffle for multiple reasons - to hide work in progress, to release new features, to give beta access to other features, and to handle different customer "plans". As a result, we have a lot of flags in play, and they have become hard to manage.

It would be really helpful to have a `Flag.category` (`label`, `tag`, ...) field to be able to manage this.

* Add CharField to the Flag model (free text)
* Add field to admin list view
* Add field to admin list filters

**Comment by clintonb** [comment]
I’m hesitant to add this type of metadata for everyone. Most who need this use a naming scheme (e.g., `billing.enable_annual_plan`). Would this meet your needs?

**Comment by hugorodgerbrown** [comment]
We already use a naming scheme, but tbh it's a pain as you can't easily filter / view in the admin list view. I understand if you don't want to merge this - we can run off our fork if we decide to go with this.

**Comment by hugorodgerbrown** [comment]
Closing this as per @clintonb's comment.
