### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by David-Guillot** [django-waffle/django-waffle#371]
Hi there,

I see some changes since the latest release (0.20.0). In semver these changes would require a major version (since it's dropping support for Python2) ; what is left in the way of `django-waffle` **1.0.0**?

Thanks :)

**Comment by clintonb** [comment]
You raise a valid point. There is nothing blocking a 1.0.0 release. I will work on that this week.

**Comment by chrisrodz** [comment]
Hey @clintonb wondering if there's been an update on this?

Would love to see 1.0.0 released 😄

**Comment by David-Guillot** [comment]
Thanks @clintonb 👍 🚀
