### ISSUE TITLE
AbstractBaseFlag uses deprecated NullBooleanField

### ISSUE THREAD

**Issue by washeck** [django-waffle/django-waffle#376]
[AbstractBaseFlag.everyone](https://github.com/django-waffle/django-waffle/blob/a8fc0f2ba636ab4520ae28d6dcb9d0d38f0b5905/waffle/models.py#L131) is a `NullBooleanField`. Django docs has been recommending to use `BooleanField(null=True)` and Django 3.1 pushed this even further making `NullBooleanField` deprecated.

**Comment by hugorodgerbrown** [comment]
This will be a breaking change - the `BooleanField` only accepts a `null=True` argument in 2.1+, which means that 1.11 and 2.0 will have to be dropped in order to fix this.
