### ISSUE TITLE
Default auto field not configured

### ISSUE THREAD

**Issue by con-cat** [django-waffle/django-waffle#396]
[In Django 3.2](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys), you can customise the type of auto-created primary key fields by configuring `DEFAULT_AUTO_FIELD` in your settings.

My project has recently been upgraded to Django 3.2, and I set `DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'`, because Django is making this the new default (previously it was `AutoField`). However, after doing that, the `makemigrations` command generates migrations to change this for dependencies that don't have a default configured, as well as first-party apps.

My project runs `makemigrations --check` in CI, and that now fails because it thinks waffle is missing a migration.

This could be addressed by adding `default_auto_field = 'django.db.models.AutoField'` to `WaffleConfig` - I'd be happy to make a PR to do that.

This also relates to issue #395

**Comment by clintonb** [comment]
Please create a PR.

**Comment by con-cat** [comment]
@clintonb I've made a PR :)
