### ISSUE TITLE
is_active_for_user() doesn't respect flag.everyone

### ISSUE THREAD

**Issue by alexrudy** [django-waffle/django-waffle#401]
This was surprising to me – `is_active_for_user()` is exposed as a public API function, so I thought it would handle `flag.everyone`, but it doesn't respect that setting. That makes sense to me for `_is_active_for_user()` (which happens after the check on `.everyone` in `is_active()`, but makes for unexpected behavior when trying to use flags outside of a request context (where `is_active_for_user()` feels like the right API to use...

I would expect there to be a simple way to check if a flag is active without a request (e.g. in a celery task) but instead I have to ensure that I check the `.everyone` field separately. Is this intended? Could the API be changed so that `is_active_for_user()` resepects `.everyone`?

**Comment by jezeniel** [comment]
Yes should this be implemented?
