### ISSUE TITLE
contextfunction is deprecated in Jinja2 3

### ISSUE THREAD

**Issue by willkg** [django-waffle/django-waffle#402]
When running django-waffle 2.2.0 with Jinja2 3.0.1, I get this error:

```
DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
```

from this code:

https://github.com/django-waffle/django-waffle/blob/7990411c5590571665f357cabaf9e5535deb0826/waffle/jinja.py#L10

The deprecation is mentioned in the Jinja2 3.0.0 changes:

https://jinja.palletsprojects.com/en/3.0.x/changes/?highlight=contextfunction#version-3-0-0

**Comment by willkg** [comment]
I think a possible fix here that supports Jinja2 2 and 3 is something goofy like:

```
try:
    from jinja2 import pass_context as pass_context
except ImportError:
    # NOTE(willkg): We can get rid of this when we stop supporting Jinja2 < 3.
    from jinja2 import contextfunction as pass_context
```

Then change the decorator to `@pass_context`.

Is it helpful for me to throw that into a PR?

**Comment by clintonb** [comment]
Yes, please open a PR. Thanks!

**Comment by clintonb** [comment]
v2.2.1 has been released with this fix.
