### ISSUE TITLE
Waffle should be able to auto-create flags/switches/samples

### ISSUE THREAD

**Issue by wolph** [django-waffle/django-waffle#44]
Manually having to create these is kind of tedious and unneeded.

Automatically creating them if they don't exist (configurable with a setting of course) would be better :)

**Comment by tobych** [comment]
See my #50 too, about defining switches and default states in settings.

**Comment by tbarbugli** [comment]
will this ever happen? as @WoLpH said 3 years ago, this is unneeded and tedious.

**Comment by jsocol** [comment]
Honestly, it's never been high on my list. There are a bunch of other refactors [that should happen first](https://github.com/jsocol/django-waffle/milestones/0.11.1), but I did stick this in [milestone 0.12](https://github.com/jsocol/django-waffle/milestones/0.12).

The biggest issue is that, in my day to day of using waffle for the past however many years, it's never been enough of a pain point to deal with the fallout of trying to do it.
1. Creating them out of request/response cycles requires a level of code analysis that's just not worth including. Looking at Python and multiple types of templates, evaluating expressions that get used as flag names, etc. Or it requires a huge change of listing all the names somewhere.
2. Creating them during request/response cycles is the winner, but it doesn't necessarily get you the full set, and requires handling a bunch of race/concurrency issues that don't come up if we don't do it.

And like I said, it's never bothered me nearly enough for me to say "OK, I'm going to fix this now."

**Comment by tbarbugli** [comment]
Not being passive aggressive here, but this is annoying enough for me to look at other solutions such as  Gutter. feature flipping libs should be as simple as it can get, sync'ing keys manually is clearly not human friendly and it is prone to error.

**Comment by jsocol** [comment]
Is it annoying enough to help contribute a solution? I'm open to it, but, like I said, it's never tripped my personal "too annoying gotta fix" breaker.

Otherwise, yep, there definitely are other solutions out there that might fit your needs better.

**Comment by wolph** [comment]
Well, to be fair. I already created a pull request 3 years ago to fix this. So there was already a contributed solution ;)
I still think some high-performance solution needs to be there. The `get_or_create` method suggested in some related discussions is exactly what you are trying to avoid with a package such as waffle.

**Comment by adamhaney** [comment]
I'd be interested in contributing a patch for this if it would be accepted. My plan would be to create a settings value (WAFFLE_CREATE_MISSING_FLAGS, WAFFLE_CREATE_MISSING_SWITCHES, etc. although I'm open to feedback on naming). To avoid changing historic behavior the setting could be off by default, but perhaps allow those that are interested to enable it so that when a flag/switch is encountered it could be automatically created and respect the WAFFLE_FLAG_DEFAULT, WAFFLE_SWITCH_DEFAULT, WAFFLE_SAMPLE_DEFAULT values on creation).

**Comment by asfaltboy** [comment]
@WoLpH , can this be closed, since we now have those `WAFFLE_CREATE_MISSING_X` options?

**Comment by wolph** [comment]
Yes, I believe so :)

Honestly, I'm currently not using Waffle so I cannot easily check anymore. But I might use it again for a project soon.
