### ISSUE TITLE
Latest migrations file has incorrect model definitions

### ISSUE THREAD

**Issue by zmsmith** [django-waffle/django-waffle#47]

**Comment by cyberdelia** [comment]
Can you be more precise ?

**Comment by zmsmith** [comment]
wow. fast response

**Comment by zmsmith** [comment]
fix is here:
https://github.com/Yipit/django-waffle/commit/2197b022f39a1b75fc5d50ef81ecd5a1022de737

**Comment by zmsmith** [comment]
those fields all exist in the models but not in the migration 0008 file, which they should.

**Comment by jsocol** [comment]
Thanks, I cherry-picked 2197b022f39a1b75fc5d50ef81ecd5a1022de737.
