### ISSUE TITLE
'switch' is a reserved word in JavaScript, so waffle.switch() should probably be renamed

### ISSUE THREAD

**Issue by tobych** [django-waffle/django-waffle#48]
My IDE is having a fit, although the code is working for me.

**Comment by jsocol** [comment]
Yeah, it almost certainly should. Any suggestions? "switch_is_active" is more verbose but nice and not reserved. I guess I'd want to make it consistent with the flag and sample methods.

**Comment by tobych** [comment]
Well, it could be a corrupted version of the word "switch", like the way people use "klass". That's a fine tradition, but not one you'd want to dive into without being sure, I guess. "switch_is_active" works but is indeed a little long. That's what Gargoyle uses though, along with "is_active" in other contexts. You'll want to distinguish between switch_is_active and flag_is_active though I suppose, unless you can assume that you'll not have a switch, flag and perhaps sample with the same name. Perhaps if you made that a new rule, you could just have waffle.active(name). Otherwise I guess I'd go with switch_is_active, flag_is_active and sample_is_active.

I've read one person describing "klass" as a "creative mispelling". Perhaps there's already such a thing for "switch" that's been settled upon but I'm not aware. And "klass" is actually Swedish for "class". Perhaps you could find a similar foreign variant of "switch" to use here. Looks like "strömbrytare" might be the Swedish translation for "switch"... maybe not that then... I guess the Swedes having a word that is so close to "class" was a lucky strike. The Spanish seems to be "interruptor". This is probably a wild goose chase at this point, but it's been fun.

**Comment by jsocol** [comment]
Fixed by #49. Thanks, Toby!

**Comment by piotrkilczuk** [comment]
Great you fixed that, it was breaking the JS on Android Webkit.

My workaround just if anyone is stuck with 0.8:

```
if (waffle['switch']('switchname') !== true) {
    return;
}
```

**Comment by tobych** [comment]
Ah, that's good news. Nice workaround.
