### ISSUE TITLE
Be able to set/create switch states in code more easily

### ISSUE THREAD

**Issue by tobych** [django-waffle/django-waffle#51]
I currently have this in code I'm using to build test fixtures:

```
    Switch.objects.create(name='avoid_accidental_drags', active=True)
```

If this switch already exists, I'm in trouble. I'd like a way of setting the state of a switch. And of having it autocreated (also #44) if necessary.

I can probably work on this as I'll want this in production soon. Comments please!

**Comment by jsocol** [comment]
You can always use `Switch.objects.get_or_create`, but if it's your test database, you should know the state ahead of time (e.g. it should be empty or not).
