### ISSUE TITLE
Be able to set switch states in JavaScript

### ISSUE THREAD

**Issue by tobych** [django-waffle/django-waffle#59]
I want to set switch states from the JavaScript console to help debug my code.

**Comment by jsocol** [comment]
Actually I think this has always been possible:

```js
> console.log(waffle.FLAGS);
> waffle.FLAGS['my_flag'] = true;
> waffle.flag_is_active('my_flag');
```

Similar for `SWITCHES` and `SAMPLES`.

I'm facepalming pretty hard I never noticed that.

**Comment by jsocol** [comment]
Sorry, not _always_, just since #97!
