### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by tachang** [django-waffle/django-waffle#61]
Documentation is off. The querystring parameter will be just the name_of_flag. No dwft prefix. Had to look it up in source code. :)

The querystring parameter will be dwft_<name_of_flag>. For example, if I have a flag named “ab_testing”, then I can override the setting with these urls:

```
http://example.com/?dwft_ab_testing=0 – Off
http://example.com/?dwft_ab_testing=1 – On
```

**Comment by jsocol** [comment]
Already fixed in #56. Thanks!
