### ISSUE TITLE
make A/B testing use case easier

### ISSUE THREAD

**Issue by willkg** [django-waffle/django-waffle#62]
We (SUMO) use waffle for A/B testing of behavior in the search view. One problem with this is that in order to derive CTR metrics for the A/B test so we can see whether it's helping/hindering, we need to thread the waffle flag name and value into all the search forms on the site and then also in the urls for search results.

This is a pain in the ass.

It's probably the case that we could alleviate some of the annoyingness in the SUMO code by centralizing a bunch of that code. However, James contends that waffle could/should make this easier regardless.

**Comment by jsocol** [comment]
I was thinking about how I'd do this today and I've decided I was wrong. What I have done, and worked well, and I'd do again, is to set custom session variables with Google Analytics and then use their segmenting and goal definitions to look at results. Obviously not everyone uses GA, but I have to imagine other platforms have similar features. Also: I've never gotten close to figuring out a way to do this within Waffle.
