### ISSUE TITLE
Spaces in Flag/Switch/Sample's fail when using Memcache

### ISSUE THREAD

**Issue by silent1mezzo** [django-waffle/django-waffle#63]
If you're using Memcache as your cache backend and have a space in your Flag, Switch or Sample name memcache throws and error on saving. `MemcachedKeyCharacterError: Control characters not allowed`

This is because with Memcache you can't have spaces in the key.

**Comment by silent1mezzo** [comment]
Here's a couple solutions I could think of:
- Add a `slug` field to Flags, Switches and Samples defaulting to the name.
- Replace spaces from the name when setting the cache
- Don't do anything and specify that Memcache isn't supported.

I can't think of a solution that would be backwards compatible since the first two options would change the cache keys.

**Comment by jsocol** [comment]
My inclination is either to document "don't use spaces" (everyone I know seems to uses dashes) or replace some part of the cache key with a digest of itself. Falling off cache momentarily while upgrading isn't a concern, but Memcache is definitely supported.

**Comment by jsocol** [comment]
Which Memcache client are you using?

**Comment by silent1mezzo** [comment]
I'm using python-memcached. Documenting it would work to but I'd be worried of people testing it out and having it fail and then just leaving without looking at the docs.

Using a digest would probably work the best.

**Comment by jsocol** [comment]
Yeah, the MD5 of everything except the overall prefix should work.

On Monday, November 12, 2012 11:22:49 AM, Adam McKerlie wrote:

> I'm using python-memcached. Documenting it would work to but I'd be
> worried of people testing it out and having it fail and then just
> leaving without looking at the docs.
> 
> Using a digest would probably work the best.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jsocol/django-waffle/issues/63#issuecomment-10293780.

## 

James Socol
Community Platforms Manager
james@mozilla.com
@jamessocol

**Comment by silent1mezzo** [comment]
Writing up a pull request that'll md5 the name and use the digest for the key

**Comment by jsocol** [comment]
Thanks!

**Comment by silent1mezzo** [comment]
Do you have a list of requirements for tests? So far I've seen nose, mock but I'm not sure where test_utils are.

As an FYI, tests all fail when you're just using Django's default test runner.

**Comment by jsocol** [comment]
`pip install -r requirements.txt`, it's covered [in the docs](http://waffle.readthedocs.org/en/latest/contributing.html).

Tests are not written with the Django test runner in mind.

**Comment by silent1mezzo** [comment]
Doh! Should have read the docs closer...

**Comment by jsocol** [comment]
Closed by #64.
