### ISSUE TITLE
No good way to get info on what flags/switches were active for a given request

### ISSUE THREAD

**Issue by katzj** [django-waffle/django-waffle#67]
When doing reporting of errors, it'd be nice to be able to have a method to get a hash of active flag/switches/samples which were on for the request.  There's not really a great way to do that right now although the basics are all there in wafflejs.

Would you be open to a patch that pulled such a thing into a utility function that can be used by wafflejs as well as able to be used for error reporting purposes?  If so, I can do the quick refactor and pull request.

**Comment by joeyespo** [comment]
+1
