### ISSUE TITLE
WAFFLE_SWITCH_DEFAULT does not change the behaviour of waffle.js

### ISSUE THREAD

**Issue by jameskeane** [django-waffle/django-waffle#72]
Neither, WAFFLE_SWITCH_DEFAULT, WAFFLE_FLAG_DEFAULT, or WAFFLE_SAMPLE_DEFAULT have any effect on the waffle.js script.

**Comment by jsocol** [comment]
Yup. They should. My bad.

**Comment by jameskeane** [comment]
I'll have a pull request ready soon, testing now.

**Comment by jsocol** [comment]
Closed by #73, thanks!
