### ISSUE TITLE
DateTimeField received a naive datetime while time zone support is active.

### ISSUE THREAD

**Issue by jameskeane** [django-waffle/django-waffle#74]
This seems to be an issue in the migrations.  

It looks as if `auto_now` and `auto_now_add` were being used previously, but a change was made to manually use datetime.now.  Why is that?

This happens for me when running tests (creating the test DB).

**Comment by jsocol** [comment]
`auto_now` and `auto_add_now` have been flirting with dislike and potential deprecation for a while. When they are used, it becomes impossible to ever override the behavior. Most people--and I am one of them--prefer to use a callable like `datetime.now` and/or a custom `save()` method that gives you more control.

But it should be sensitive to the `USE_TZ` setting, and not use a naive datetime when that's `True`.

**Comment by mwarkentin** [comment]
This should be fixed as of aba86f1b89a4dfbc9e932ffc8c7f597c8c79d094.

**Comment by jsocol** [comment]
That commit was merged in a while ago. Please re-open if anyone see this again!
