### ISSUE TITLE
Django 1.5 - Support for group-less custom users

### ISSUE THREAD

**Issue by aarose** [django-waffle/django-waffle#79]
Flags currently assume that the User model must have a 'Group' field. This was an OK assumption until Django 1.5 allowed for custom User models, which only requires these minimum requirements to be met:
1. Must have an integer primary key.
2. Must have a single unique field that can be used for identification purposes.
3. Must provide a way to address the user in a “short” and “long” form.

If a custom User is being used with no group field, flag_is_active() throws an AttributeError exception at:

user_groups = user.groups.all()

since the User object has no such attribute.

I'm currently forking this repo in order to code a simple patch (Exception catching), but it might take a while to code a test case, so that it can be merged to the main repo. Anyone can feel free to beat me to the punch.

There is also the possibility of "fancy-ing it up" by implementing a way of removing the groups field from the flag model entirely (before db tables are created) IF a Django 1.5 group-less user is being used.

---

EDIT: There's also the assumption that the User object will have a is_superuser field (also throws an AttributeError exception in flag_is_active). However, a quick workaround is just to update the custom user model to take advantage of the @ property decorator. Still, it would be nice to have waffle check if these fields exist, and handle the cases that don't.

**Comment by nkeilar** [comment]
For reference read about a workaround here http://blog.vmfarms.com/2013/07/how-to-make-waffle-compatible-with.html

**Comment by aarose** [comment]
Yup, I wrote that. :) Forgot to link to it/update this issue, thanks for adding it.

**Comment by jsocol** [comment]
Thanks for writing up the blog post! I can definitely make Waffle more defensive about those four properties, but the model still has a ManyToMany relationship to Groups, and since that's a useful feature, it's still going to be a requirement (though better documented).

**Comment by jsocol** [comment]
As of #211, waffle should be much more defensive about this. You'll still need the `Groups` model—because Flags will still have an M2M relationship to it—but your users don't actually have to have them.
