### ISSUE TITLE
Expose list of active switches and flags in wafflejs

### ISSUE THREAD

**Issue by matthewryanscott** [django-waffle/django-waffle#81]
The active flags, switches, and samples are transmitted to the client via the `wafflejs` view, but the only way they are exposed as an API is via querying a given name for existence.

For the use case of automatically inject an entire list of active flags, etc. into a namespace for rendering a template using JavaScript, I propose adding some functions to `window.waffle` that will return such lists:
- `active_flags()`
- `active_switches()`
- `active_samples()`

**Comment by coagulant** [comment]
Do we need any tests to get this merged, or this PR needs other kind of improvements?

Personally, I think the idea is good, but tests would be nice (not sure what kind, thought).

**Comment by jsocol** [comment]
I think #97 is the better way to expose this. It's simpler and there's no particular need for this to be a getter, since "be secure" has always been a non-goal of waffle.
