### ISSUE TITLE
Using DB to Persist the Flag (instead of cookie)

### ISSUE THREAD

**Issue by tayfun** [django-waffle/django-waffle#99]
What do you think of using DB (django's own auth_groups) for persisting a user's flag value once it is computed, as opposed to having a cookie?

I have a need to show consistent UI for users when they use different browsers/computers and more importantly when I send an email (there's no cookie then) so I would like to persist flag value to the DB. 

If you'd like this feature (a `sticky` attribute in Flag) then I will be adding a group with the same name as flag and check if the user is in that group or add them in to that group otherwise, according to the sample. I can code and send a PR if you'd like this.

Let me know what you think of this feature.

**Comment by jsocol** [comment]
It's definitely something that needs to be addressed (see #1) but before using groups I think some performance evaluation needs to be done on that route vs just adding the user to the user list for the flag.

I'm also planning on spending some time over the holidays doing a low-level overhaul of the architecture of Waffle, so I'd kind of warn people off doing non-trivial work on waffle right now.

**Comment by tayfun** [comment]
Thanks for the prompt reply. I had not seen issue #1.

Regarding using user or group list of flag, well I originally thought this will augment the existing ways of setting the flag value such as by adding groups or users to flags. By using an attribute such as 'sticky', it would remember flag's value if that is needed. Now that you mention it again, I think both are valid ideas.

**Comment by jsocol** [comment]
Closing in favor of #1.
